USE [master]
GO
/****** Object:  Database [ToDoDB]    Script Date: 11/12/2019 2:05:33 PM ******/
CREATE DATABASE [ToDoDB]
GO
ALTER DATABASE [ToDoDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ToDoDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ToDoDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ToDoDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ToDoDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ToDoDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ToDoDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ToDoDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ToDoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ToDoDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ToDoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ToDoDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ToDoDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ToDoDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ToDoDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ToDoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ToDoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ToDoDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ToDoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ToDoDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ToDoDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ToDoDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ToDoDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ToDoDB] SET  MULTI_USER 
GO
ALTER DATABASE [ToDoDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ToDoDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ToDoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ToDoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ToDoDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ToDoDB] SET QUERY_STORE = OFF
GO
USE [ToDoDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [ToDoDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 11/12/2019 2:05:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TaskItems]    Script Date: 11/12/2019 2:05:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaskItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[IsCompleted] [bit] NOT NULL,
 CONSTRAINT [PK_TaskItems] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20191112110431_InitialCreate', N'3.0.0')
GO
SET IDENTITY_INSERT [dbo].[TaskItems] ON 
GO
INSERT [dbo].[TaskItems] ([Id], [Title], [Description], [IsCompleted]) VALUES (1, N'ads', N'ffhhjhk', 1)
GO
SET IDENTITY_INSERT [dbo].[TaskItems] OFF
GO
USE [master]
GO
ALTER DATABASE [ToDoDB] SET  READ_WRITE 
GO
